# -*- coding: utf-8 -*-
"""Decision Tree Regressor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s1VJmdH-e2ddBcZuFBIXpZswYHDtT2Sg
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('Salaries.csv')

df.drop(['Unnamed: 8', 'Unnamed: 9','Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12','Year','JobTitle'],axis = 'columns' ,inplace = True)

df.drop([148646,148651,148652,148650], axis = 'rows',inplace = True)

x = df.iloc[:,0:5].values

x

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean' )
imputer.fit(x)
x = imputer.transform(x)

y = df.iloc[:,-1].values

from sklearn.model_selection import train_test_split
x_train ,x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state =1)

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(x, y)

y_pred = regressor.predict(x_test)

y_pred

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)