# -*- coding: utf-8 -*-
"""Multiple Regression Model

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GPgaj8BT1k1wJ9lZAOHjeTEwzLyak4MS
"""

import pandas as pd
import numpy as np

df = pd.read_csv('Salaries.csv')

df.head(11)

df.tail(11)

df.columns

df.drop(['Unnamed: 8', 'Unnamed: 9','Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12','Year','JobTitle'],axis = 'columns' ,inplace = True)

df.head(5)

df.tail(5)

df.drop([148646,148651,148652,148650], axis = 'rows',inplace = True)

df.tail(5)

x = df.iloc[:,0:5].values

x

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean' )
imputer.fit(x)
x = imputer.transform(x)

y = df.iloc[:,-1].values

y

from sklearn.model_selection import train_test_split
x_train ,x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state =1)

from sklearn.linear_model import LinearRegression
regressor =LinearRegression()
regressor.fit(x_train,y_train)

y_pred = regressor.predict(x_train)

from sklearn.metrics import r2_score
r2_score(y_train,y_pred)

y2_pred= regressor.predict(x_test)

y2_pred

r2_score(y_test,y2_pred)